# Generated by Django 5.1.5 on 2025-01-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_last_login_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hashed_password',
            new_name='password',
        ),
    ]
