# Generated by Django 5.1.5 on 2025-01-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_hashed_password_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
        migrations.AlterModelTable(
            name='folder',
            table='folders',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
